name: anaetainan CD

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      # - name: Extract branch name
      #   shell: bash
      #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      #   id: extract_branch

      - name: Push to Github Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          version: ${{ steps.extract_branch.outputs.branch }}
          file: Dockerfile
          push: true
          tags: "ghcr.io/${{ github.repository }}:${{ steps.branch-names.outputs.default_branch }}"
          #target: production


      - name: Setup SSH
        shell: bash
        run: |
         eval `ssh-agent -s`
         mkdir -p /home/runner/.ssh/
         touch /home/runner/.ssh/ansible.pem
         echo -e "${{secrets.SSH_PRIVATE_KEY}}" > /home/runner/.ssh/ansible.pem
         chmod 600 /home/runner/.ssh/ansible.pem
         #ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{secrets.SSH_HOST}} >> /home/runner/.ssh/known_hosts

      - name: Deploy using docker run
        shell: bash
        run: |
          cd devops/ansible/
          ansible-playbook --private-key /home/runner/.ssh/ansible.pem -i hosts/prod playbook.yml --tags backend
